version:  '3.8'
services:
  db:
    image: 'postgres:latest'
    restart: always
    container_name: postgres
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: authdb
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      NODE_ENV: development
      PORT: 8000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: authdb
      DB_USER: user
      DB_PASSWORD: secret
    depends_on:
       db:
         condition: service_healthy